// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeeklyPlanTracker.Infrastructure.Data;

#nullable disable

namespace WeeklyPlanTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("EstimatedEffort")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("BacklogItems");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.CategoryAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BudgetHours")
                        .HasColumnType("double precision");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanningWeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanningWeekId");

                    b.ToTable("CategoryAllocations");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.MemberPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanningWeekId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalPlannedHours")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PlanningWeekId");

                    b.ToTable("MemberPlans");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.PlanningWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionEndDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutionStartDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanningDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("TeamCapacity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlanningWeeks");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.ProgressUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("NewHoursCompleted")
                        .HasColumnType("double precision");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("PreviousHoursCompleted")
                        .HasColumnType("double precision");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskAssignmentId");

                    b.ToTable("ProgressUpdates");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.TaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("uuid");

                    b.Property<double>("CommittedHours")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("HoursCompleted")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MemberPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProgressStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("MemberPlanId");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLead")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.CategoryAllocation", b =>
                {
                    b.HasOne("WeeklyPlanTracker.Core.Entities.PlanningWeek", "PlanningWeek")
                        .WithMany("CategoryAllocations")
                        .HasForeignKey("PlanningWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanningWeek");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.MemberPlan", b =>
                {
                    b.HasOne("WeeklyPlanTracker.Core.Entities.TeamMember", "Member")
                        .WithMany("MemberPlans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyPlanTracker.Core.Entities.PlanningWeek", "PlanningWeek")
                        .WithMany("MemberPlans")
                        .HasForeignKey("PlanningWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("PlanningWeek");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.ProgressUpdate", b =>
                {
                    b.HasOne("WeeklyPlanTracker.Core.Entities.TaskAssignment", "TaskAssignment")
                        .WithMany("ProgressUpdates")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.TaskAssignment", b =>
                {
                    b.HasOne("WeeklyPlanTracker.Core.Entities.BacklogItem", "BacklogItem")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyPlanTracker.Core.Entities.MemberPlan", "MemberPlan")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("MemberPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacklogItem");

                    b.Navigation("MemberPlan");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.BacklogItem", b =>
                {
                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.MemberPlan", b =>
                {
                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.PlanningWeek", b =>
                {
                    b.Navigation("CategoryAllocations");

                    b.Navigation("MemberPlans");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.TaskAssignment", b =>
                {
                    b.Navigation("ProgressUpdates");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.TeamMember", b =>
                {
                    b.Navigation("MemberPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
